name: Lint code
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  pull_request:
    branches:    
      - master
      - integration
  jobs:
    lint-code:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.8.1'
            cache: 'pip'
        - run: pip install flake8
        - run: cd src
        - run: flake8
