name: Test
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  pull_request:
    branches:    
      - master
      - integration
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install poetry
      - run: poetry install
      - run: poetry run flake8
      - run: poetry run pytest
